[package]
name = "mithril-signer"
version = "0.2.187"
description = "A Mithril Signer"
authors = { workspace = true }
edition = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
license = { workspace = true }
repository = { workspace = true }

[[bench]]
name = "mktree_store_sqlite"
harness = false

[dependencies]
anyhow = "1.0.86"
async-trait = "0.1.82"
axum = "0.7.5"
clap = { version = "4.5.17", features = ["derive", "env"] }
config = "0.14.0"
hex = "0.4.3"
mithril-common = { path = "../mithril-common", features = ["full"] }
mithril-doc = { path = "../internal/mithril-doc" }
mithril-persistence = { path = "../internal/mithril-persistence" }
openssl = { version = "0.10.66", features = ["vendored"], optional = true }
openssl-probe = { version = "0.1.5", optional = true }
prometheus = "0.13.4"
rand_chacha = "0.3.1"
rand_core = "0.6.4"
reqwest = { version = "0.12.7", features = ["json", "stream"] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.128"
slog = { version = "2.7.0", features = [
    "max_level_trace",
    "release_max_level_debug",
] }
slog-async = "2.8.0"
slog-bunyan = "2.5.0"
slog-scope = "4.4.0"
sqlite = { version = "0.36.1", features = ["bundled"] }
thiserror = "1.0.63"
tokio = { version = "1.40.0", features = ["full"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = { version = "0.6.0", optional = true }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports", "async_tokio"] }
httpmock = "0.7.0"
mithril-common = { path = "../mithril-common" }
mockall = "0.13.0"
prometheus-parse = "0.2.5"
slog-term = "2.9.1"
warp = "0.3.7"

[features]
default = ["jemallocator"]

bundle_openssl = ["dep:openssl", "dep:openssl-probe"]
jemallocator = ["dep:tikv-jemallocator"]
